/* Generated by my-genstub.  Do not edit. */

#line 2 "stub-simple-example.scm"
#include <stdio.h>

#ifndef M_PI
#define M_PI 3.1415926535897932384
#endif


 void test1(int aa){{
#line 12 "stub-simple-example.scm"
if ((aa)>(50)){{test2();}}}}
 int test2(int argc,char** argv){{
#line 16 "stub-simple-example.scm"
{int i=0;int cise__1128=strlen((argv)[0]);for (; (i)<(cise__1128); (i)++){printf("%02x",((argv)[0])[i]);}}}}
void test111(int aaaaa);

}
